Repository Open-Web-Analytics/Open-Web-Analytics, pull requests merged in 2020-03, with the labels that each got.

#471 Bugfix: Manually provided location properties getting ignored
  modules/base/classes/trackingEventHelpers.php
Labels: Core Development, bug, hasfix

#450 Maxmind require conflicts
  modules/maxmind_geoip/classes/maxmind.php
Labels: bug, maxmind module

#487 Feature: Password change via cli command
  modules/base/changeUserPasswordCli.php
  modules/base/classes/userManager.php
  modules/base/module.php
  modules/base/usersChangePassword.php
  modules/base/usersSetPassword.php
Labels: Core Development, enhancement
