Repository Open-Web-Analytics/Open-Web-Analytics, pull requests merged in 2020-04, with the labels that each got.

#513 Refactor Controller Inheritance
  modules/base/changeUserPasswordCli.php
  modules/base/classes/userManager.php
  modules/base/installBase.php
  modules/base/installConfig.php
  modules/base/login.php
  modules/base/optionsGoalEdit.php
  modules/base/passwordResetRequest.php
  modules/base/sitesAdd.php
  modules/base/sitesEdit.php
  modules/base/sitesEditSettings.php
  modules/base/usersAdd.php
  modules/base/usersChangePassword.php
  modules/base/usersEdit.php
Labels: Review needed

#523 Feature: CLI Command to re-crawl Document URLs
  modules/base/crawlDocumentCli.php
  modules/base/entities/document.php
  modules/base/module.php
  owa_httpRequest.php
Labels: Core Development, enhancement

#535 More REST API Routes and Changes
  modules/base/classes/error.php
  modules/base/classes/mailer.php
  modules/base/classes/userManager.php
  modules/base/controllers/addSiteRestController.php
  modules/base/controllers/addUserRestController.php
  modules/base/controllers/deleteUserRestController.php
  modules/base/controllers/siteAddAllowedUserRestController.php
  modules/base/controllers/sitesRestController.php
  modules/base/controllers/usersRestController.php
  modules/base/entities/user.php
  modules/base/module.php
  modules/base/sites.php
  modules/base/sitesEditAllowedUsers.php
  modules/base/templates/restApiResponse.php
  modules/base/templates/sites_addoredit.tpl
  modules/base/users.php
  modules/base/usersAdd.php
  modules/base/usersDelete.php
  modules/base/usersNewAccount.php
  owa_controller.php
  owa_coreAPI.php
  owa_entity.php
  owa_requestContainer.php
  plugins/validations/inArray.php
  plugins/validations/isNotCurrentUser.php
Labels: Core Development, REST API

#536 Even more rest api
  modules/base/classes/resultSetManager.php
  modules/base/classes/service.php
  modules/base/classes/settings.php
  modules/base/controllers/reportsRestController.php
  modules/base/controllers/usersRestController.php
  modules/base/js/owa.heatmap.js
  modules/base/js/owa.reporting-combined-min.js
  modules/base/js/owa.resultSetExplorer.js
  modules/base/module.php
  modules/base/reportBrowserDetail.php
  modules/base/reportDashboard.php
  modules/base/reportTransactionDetail.php
  modules/base/reportVisit.php
  modules/base/reportVisitor.php
  modules/base/reportVisitors.php
  modules/base/templates/report_actionDetail.php
  modules/base/templates/report_actionTracking.php
  modules/base/templates/report_anchortext.tpl
  modules/base/templates/report_commerce.php
  modules/base/templates/report_content.tpl
  modules/base/templates/report_dashboard.tpl
  modules/base/templates/report_dimensionDetail.php
  modules/base/templates/report_dimensionDetailNoTabs.php
  modules/base/templates/report_dimensionalTrend.php
  modules/base/templates/report_document.tpl
  modules/base/templates/report_dom_clicks.php
  modules/base/templates/report_ecommerce.php
  modules/base/templates/report_goal_funnel.php
  modules/base/templates/report_goals.php
  modules/base/templates/report_latest_visits.tpl
  modules/base/templates/report_traffic.tpl
  modules/base/templates/report_transaction_detail.php
  modules/base/templates/report_transactions.php
  modules/base/templates/report_trend_section.php
  modules/base/templates/report_visit.tpl
  modules/base/templates/report_visitor.tpl
  modules/base/templates/report_visitors.tpl
  modules/base/templates/restApiResponse.php
  modules/base/templates/sites.tpl
  owa_coreAPI.php
  owa_module.php
  owa_template.php
  owa_view.php
  wp_plugin.php
Labels: REST API

#533 Feature: Added search engine duckduckgo
  modules/base/classes/client.php
  modules/base/js/owa.tracker-combined-min.js
  modules/base/js/owa.tracker.js
Labels: enhancement

#534 Feature: Domstream screen resolution
  modules/base/entities/domstream.php
  modules/base/js/owa.tracker-combined-min.js
  modules/base/js/owa.tracker.js
  modules/base/module.php
  modules/base/overlayLauncher.php
  modules/base/templates/player_overlay.tpl
  modules/base/templates/report_domstreams.tpl
  modules/base/updates/010.php
  modules/domstream/handlers/domstreamHandlers.php
  modules/domstream/module.php
  owa_controller.php
Labels: enhancement

#557 Reporting Pages Design refresh
  modules/base/css/font-awesome/css/all.min.css
  modules/base/css/font-awesome/webfonts/fa-brands-400.eot
  modules/base/css/font-awesome/webfonts/fa-brands-400.svg
  modules/base/css/font-awesome/webfonts/fa-brands-400.ttf
  modules/base/css/font-awesome/webfonts/fa-brands-400.woff
  modules/base/css/font-awesome/webfonts/fa-brands-400.woff2
  modules/base/css/font-awesome/webfonts/fa-regular-400.eot
  modules/base/css/font-awesome/webfonts/fa-regular-400.svg
  modules/base/css/font-awesome/webfonts/fa-regular-400.ttf
  modules/base/css/font-awesome/webfonts/fa-regular-400.woff
  modules/base/css/font-awesome/webfonts/fa-regular-400.woff2
  modules/base/css/font-awesome/webfonts/fa-solid-900.eot
  modules/base/css/font-awesome/webfonts/fa-solid-900.svg
  modules/base/css/font-awesome/webfonts/fa-solid-900.ttf
  modules/base/css/font-awesome/webfonts/fa-solid-900.woff
  modules/base/css/font-awesome/webfonts/fa-solid-900.woff2
  modules/base/css/owa.css
  modules/base/css/owa.report.css
  modules/base/css/owa.reporting-css-combined.css
  modules/base/js/owa.piechart.js
  modules/base/js/owa.reporting-combined-min.js
  modules/base/js/owa.tracker-combined-min.js
  modules/base/module.php
  modules/base/report.php
  modules/base/templates/filter_site.php
  modules/base/templates/header.tpl
  modules/base/templates/report.tpl
  modules/base/templates/report_dashboard.tpl
  modules/base/templates/report_nav.tpl
  owa_module.php
  owa_template.php
Labels: enhancement

#519 Feature: Added document visits to page details
  modules/base/module.php
  modules/base/reportDashboard.php
  modules/base/reportDocument.php
  modules/base/reportVisits.php
  modules/base/reportVisitsGeolocation.php
  modules/base/templates/report_document.tpl
  modules/base/templates/report_latest_visits.tpl
Labels: Core Development, enhancement

#560 WordPress Plugin Changes
  modules/base/templates/users_change_password.tpl
  modules/base/usersChangePassword.php
  modules/base/usersPasswordEntry.php
  modules/base/usersSetPassword.php
  owa_caller.php
  wp_plugin.php
Labels: WordPress

#567 BUG: Heatmap & domstream fixes
  .htaccess
  api.php
  modules/base/classes/resultSetManager.php
  modules/base/classes/settings.php
  modules/base/controllers/reportsRestController.php
  modules/base/js/owa.js
  modules/base/js/owa.player.js
  modules/base/js/owa.tracker-combined-min.js
  modules/base/js/owa.tracker.js
  modules/base/module.php
  modules/base/overlayLauncher.php
  modules/base/reportDomstreams.php
  modules/base/templates/report_dimensionalTrend.php
  modules/base/templates/report_document.tpl
  modules/base/templates/report_domstreams.tpl
  modules/domstream/controllers/domstreamsRestController.php
  modules/domstream/module.php
  owa_auth.php
  owa_coreAPI.php
  owa_lib.php
  owa_module.php
  owa_template.php
Labels: Domstreams, REST API, bug

#563 Feature: Rewrite REST URLs
  modules/base/templates/config_dom.tpl
  owa_template.php
Labels: Core Development, REST API, enhancement

#579 Feature: JavaScript Tracker Hooks Framework
  modules/base/js/owa.js
  modules/base/js/owa.tracker-combined-min.js
  modules/base/js/owa.tracker.js
  wp_plugin.php
Labels: Core Development, enhancement
